This is a testharness.js-based test.
FAIL ReadableStream.prototype.pipeThrough should work generically on its this and its arguments Cannot read property 'call' of undefined
PASS ReadableStream.prototype.pipeThrough should throw when its first argument is not convertible to an object 
PASS ReadableStream.prototype.pipeThrough should throw when "this" has no pipeTo method 
FAIL ReadableStream.prototype.pipeThrough should rethrow errors from accessing pipeTo, readable, or writable assert_throws: pipeThrough should rethrow the error thrown by pipeTo function "() => ReadableStream.prototype.pipeThrough.call(throwingPipeTo, { readable: { }, writable: { } }, {})" threw object "TypeError: Cannot read property 'call' of undefined" ("TypeError") expected object "Error: potato" ("Error")
FAIL ReadableStream.prototype.pipeThrough should work with missing readable, writable, or options Cannot read property 'call' of undefined
Harness: the test ran to completion.

